# Generated by Django 5.2 on 2025-05-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=100)),
                ('manufacture', models.CharField(default='Allieva Pharma Private Limited', max_length=100)),
                ('form', models.CharField(default='', max_length=100)),
                ('country_of_origin', models.CharField(default='India', max_length=50)),
                ('packing', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('descriptions', models.TextField()),
                ('uses', models.TextField()),
                ('side_effects', models.TextField()),
                ('dosage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
        ),
    ]
