# Generated by Django 5.2 on 2025-06-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
