# Generated by Django 5.2 on 2025-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobtag_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='urgent',
            field=models.CharField(max_length=50),
        ),
    ]
