# Generated by Django 5.2 on 2025-09-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
