# Generated by Django 5.2 on 2025-12-27 09:33

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to=app.models.csv_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
